use aikenflow_ir::{
    sanitize_aiken_identifier, to_pascal_case, to_snake_case, Constraint, GeneratedFiles, Protocol,
    StateDecl, TransitionDecl,
};
use std::collections::BTreeSet;

pub fn generate(protocol: &Protocol) -> GeneratedFiles {
    let mut files = GeneratedFiles::default();
    files.push("aiken.toml", generate_manifest(protocol));
    files.push("README.md", generate_contract_readme(protocol));

    for state in protocol.states.iter().filter(|state| {
        protocol.transitions.iter().any(|transition| {
            transition
                .inputs
                .iter()
                .any(|input| input.state == state.name)
        })
    }) {
        files.push(
            format!(
                "validators/{}_{}.ak",
                to_snake_case(&protocol.name),
                to_snake_case(&state.name)
            ),
            generate_state_validator(protocol, state),
        );
    }

    files
}

fn generate_manifest(protocol: &Protocol) -> String {
    let package_name = format!("aikenflow/{}", to_snake_case(&protocol.name));
    format!(
        r#"name = "{package_name}"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Generated Aiken validators for the {name} protocol"

[repository]
user = "aikenflow"
project = "{snake}"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
"#,
        name = protocol.name,
        snake = to_snake_case(&protocol.name)
    )
}

fn generate_contract_readme(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {} Aiken Contracts\n\n", protocol.name));
    out.push_str("Generated by AikenFlow.\n\n");
    out.push_str("This output is intentionally readable. Review the generated constraints before using the validators in production.\n\n");
    out.push_str("The contracts are generated from AikenFlow IR. Repository outlines and agent-context files are not used as compiler semantics.\n\n");
    out.push_str("## Layout\n\n");
    out.push_str("- `aiken.toml` contains Aiken package metadata and dependencies.\n");
    out.push_str("- `validators/` contains application validators.\n\n");
    out.push_str("## Validators\n\n");

    for state in &protocol.states {
        let transitions: Vec<_> = protocol.transitions_consuming_state(&state.name).collect();
        if transitions.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "- `{}` handles transitions: {}\n",
            state.name,
            transitions
                .iter()
                .map(|transition| transition.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    out.push_str("\n## Build\n\n```bash\naiken check\naiken build\n```\n");
    out
}

fn generate_state_validator(protocol: &Protocol, state: &StateDecl) -> String {
    let transitions: Vec<&TransitionDecl> =
        protocol.transitions_consuming_state(&state.name).collect();
    let imports = generate_imports(state, &transitions);
    let datum_name = format!("{}Datum", to_pascal_case(&state.name));
    let redeemer_name = format!("{}Redeemer", to_pascal_case(&state.name));
    let validator_name = format!(
        "{}_{}",
        sanitize_aiken_identifier(&protocol.name),
        sanitize_aiken_identifier(&state.name)
    );

    let mut out = String::new();
    out.push_str("// Generated by AikenFlow. Review before production use.\n");
    out.push_str(&imports);
    out.push('\n');
    out.push_str(&generate_datum_type(state, &datum_name));
    out.push('\n');
    out.push_str(&generate_redeemer_type(&transitions, &redeemer_name));
    out.push('\n');
    out.push_str(&format!("validator {validator_name} {{\n"));
    out.push_str(&format!(
        "  spend(datum_opt: Option<{datum_name}>, redeemer: {redeemer_name}, _own_ref: OutputReference, self: Transaction) {{\n"
    ));
    out.push_str("    expect Some(datum) = datum_opt\n\n");
    out.push_str("    when redeemer is {\n");

    for transition in transitions {
        out.push_str(&generate_redeemer_branch(state, transition));
    }

    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("}\n");
    out
}

fn generate_imports(state: &StateDecl, transitions: &[&TransitionDecl]) -> String {
    let mut lines = BTreeSet::new();
    lines.insert("use cardano/transaction.{OutputReference, Transaction}".to_owned());

    if state
        .datum
        .iter()
        .any(|field| map_aiken_type(&field.ty) == "VerificationKeyHash")
    {
        lines.insert("use aiken/crypto.{VerificationKeyHash}".to_owned());
    }

    if state
        .datum
        .iter()
        .any(|field| map_aiken_type(&field.ty) == "Address")
    {
        lines.insert("use cardano/address.{Address}".to_owned());
    }

    if transitions.iter().any(|transition| {
        transition
            .constraints
            .iter()
            .any(|constraint| matches!(constraint, Constraint::SignedBy(_)))
    }) {
        lines.insert("use aiken/collection/list".to_owned());
    }

    if transitions.iter().any(|transition| {
        transition
            .constraints
            .iter()
            .any(|constraint| matches!(constraint, Constraint::Before(_) | Constraint::After(_)))
    }) {
        lines.insert("use aiken/interval".to_owned());
    }

    let mut out = String::new();
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out
}

fn generate_datum_type(state: &StateDecl, datum_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("pub type {datum_name} {{\n"));

    if state.datum.is_empty() {
        out.push_str("  aikenflow_unit: Int,\n");
    } else {
        for field in &state.datum {
            out.push_str(&format!(
                "  {}: {},\n",
                sanitize_aiken_identifier(&field.name),
                map_aiken_type(&field.ty)
            ));
        }
    }

    out.push_str("}\n");
    out
}

fn generate_redeemer_type(transitions: &[&TransitionDecl], redeemer_name: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("pub type {redeemer_name} {{\n"));

    if transitions.is_empty() {
        out.push_str("  Noop\n");
    } else {
        for transition in transitions {
            out.push_str(&format!("  {}\n", to_pascal_case(&transition.name)));
        }
    }

    out.push_str("}\n");
    out
}

fn generate_redeemer_branch(state: &StateDecl, transition: &TransitionDecl) -> String {
    let variant = to_pascal_case(&transition.name);
    let checks = transition
        .constraints
        .iter()
        .enumerate()
        .filter_map(|(index, constraint)| constraint_to_check(state, constraint, index))
        .collect::<Vec<_>>();

    let mut out = String::new();
    out.push_str(&format!("      {variant} -> {{\n"));

    if checks.is_empty() {
        out.push_str("        True\n");
    } else {
        for check in &checks {
            out.push_str(&format!(
                "        let {} = {}\n",
                check.name, check.expression
            ));
        }

        if checks.len() == 1 {
            out.push_str(&format!("        {}\n", checks[0].name));
        } else {
            out.push_str("        and {\n");
            for check in &checks {
                out.push_str(&format!("          {},\n", check.name));
            }
            out.push_str("        }\n");
        }
    }

    out.push_str("      }\n");
    out
}

#[derive(Debug)]
struct AikenCheck {
    name: String,
    expression: String,
}

fn constraint_to_check(
    state: &StateDecl,
    constraint: &Constraint,
    index: usize,
) -> Option<AikenCheck> {
    let name = format!(
        "must_{}_{}",
        sanitize_aiken_identifier(&constraint.label()),
        index + 1
    );
    let expression = match constraint {
        Constraint::SignedBy(expr) => {
            let field = resolve_datum_field_expr(state, expr)?;
            format!("list.has(self.extra_signatories, datum.{field})")
        }
        Constraint::After(expr) => {
            let field = resolve_datum_field_expr(state, expr)?;
            format!("self.validity_range |> interval.is_entirely_after(datum.{field})")
        }
        Constraint::Before(expr) => {
            let field = resolve_datum_field_expr(state, expr)?;
            format!("self.validity_range |> interval.is_entirely_before(datum.{field})")
        }
        Constraint::Positive(expr) => {
            let field = resolve_datum_field_expr(state, expr)?;
            format!("datum.{field} > 0")
        }
        Constraint::DatumFieldEquals { field, value } => {
            let field = resolve_datum_field_expr(state, field)?;
            let value = resolve_datum_field_expr(state, value)
                .map(|value_field| format!("datum.{value_field}"))
                .unwrap_or_else(|| literal_to_aiken(value));
            format!("datum.{field} == {value}")
        }
        Constraint::CustomAiken(expr) => {
            return Some(AikenCheck {
                name,
                expression: expr.clone(),
            });
        }
        Constraint::ValuePreserved(_)
        | Constraint::OutputExists(_)
        | Constraint::Unknown { .. } => return None,
    };

    Some(AikenCheck { name, expression })
}

fn resolve_datum_field_expr(state: &StateDecl, expr: &str) -> Option<String> {
    let trimmed = expr.trim().trim_matches('"');
    let candidate = trimmed
        .strip_prefix("datum.")
        .or_else(|| trimmed.strip_prefix('$'))
        .unwrap_or(trimmed);
    let candidate = sanitize_aiken_identifier(candidate);

    state
        .datum
        .iter()
        .any(|field| sanitize_aiken_identifier(&field.name) == candidate)
        .then_some(candidate)
}

fn literal_to_aiken(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.parse::<i64>().is_ok() || matches!(trimmed, "True" | "False") {
        trimmed.to_owned()
    } else {
        format!("@\"{}\"", trimmed.replace('"', "\\\""))
    }
}

fn map_aiken_type(ty: &str) -> &'static str {
    match ty.trim() {
        "PubKeyHash" | "VerificationKeyHash" | "VKeyHash" => "VerificationKeyHash",
        "Lovelace" | "POSIXTime" | "Integer" | "Int" | "Natural" => "Int",
        "Bool" | "Boolean" => "Bool",
        "ByteArray" | "Bytes" => "ByteArray",
        "Address" => "Address",
        _ => "Data",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use aikenflow_ir::{
        Constraint, FieldDecl, InvariantDecl, StateInput, StateOutput, TransitionDecl,
    };
    use std::collections::BTreeMap;

    #[test]
    fn generates_vault_validator_with_current_handler_shape() {
        let protocol = Protocol {
            name: "SimpleVault".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![
                    FieldDecl {
                        name: "owner".to_owned(),
                        ty: "PubKeyHash".to_owned(),
                    },
                    FieldDecl {
                        name: "deadline".to_owned(),
                        ty: "POSIXTime".to_owned(),
                    },
                ],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Withdraw".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: Vec::<StateOutput>::new(),
                mints: vec![],
                burns: vec![],
                constraints: vec![
                    Constraint::SignedBy("datum.owner".to_owned()),
                    Constraint::After("datum.deadline".to_owned()),
                ],
                effects: vec![],
            }],
            invariants: Vec::<InvariantDecl>::new(),
        };

        let files = generate(&protocol);
        let validator = files
            .files
            .iter()
            .find(|file| file.path.ends_with(".ak"))
            .expect("validator file")
            .content
            .as_str();

        assert!(validator.contains("spend(datum_opt: Option<LockedDatum>"));
        assert!(validator.contains("list.has(self.extra_signatories, datum.owner)"));
        assert!(validator.contains("interval.is_entirely_after(datum.deadline)"));
    }

    #[test]
    fn unknown_value_constraints_are_left_out_of_onchain_code() {
        let state = StateDecl {
            name: "Locked".to_owned(),
            datum: vec![],
            script: None,
            terminal: false,
        };
        assert!(constraint_to_check(&state, &Constraint::ValuePreserved(None), 0).is_none());
        assert!(BTreeMap::<String, String>::new().is_empty());
    }

    #[test]
    fn positive_constraints_reject_zero_onchain() {
        let state = StateDecl {
            name: "Locked".to_owned(),
            datum: vec![FieldDecl {
                name: "amount".to_owned(),
                ty: "Lovelace".to_owned(),
            }],
            script: None,
            terminal: false,
        };

        let check =
            constraint_to_check(&state, &Constraint::Positive("datum.amount".to_owned()), 0)
                .expect("positive check");

        assert_eq!(check.expression, "datum.amount > 0");
    }

    #[test]
    fn empty_datum_uses_unit_marker() {
        let state = StateDecl {
            name: "Open".to_owned(),
            datum: vec![],
            script: None,
            terminal: false,
        };

        let datum = generate_datum_type(&state, "OpenDatum");

        assert!(datum.contains("aikenflow_unit: Int"));
        assert!(!datum.contains("temporary_field"));
    }
}
