use aikenflow_ir::{
    to_camel_case, to_pascal_case, to_snake_case, Constraint, GeneratedFiles, Protocol, StateDecl,
    StateOutput, TransitionDecl,
};
use std::collections::BTreeSet;

pub fn generate(protocol: &Protocol) -> GeneratedFiles {
    let mut files = GeneratedFiles::default();
    files.push("package.json", generate_package_json(protocol));
    files.push("tsconfig.json", generate_tsconfig());
    files.push("README.md", generate_readme(protocol));
    files.push("src/types.ts", generate_types(protocol));
    files.push("src/index.ts", generate_index(protocol));
    files
}

fn generate_package_json(protocol: &Protocol) -> String {
    format!(
        r#"{{
  "name": "@aikenflow/{name}-offchain",
  "version": "0.1.0",
  "type": "module",
  "private": true,
  "scripts": {{
    "check": "tsc --noEmit"
  }},
  "devDependencies": {{
    "typescript": "^5.8.0"
  }}
}}
"#,
        name = to_snake_case(&protocol.name).replace('_', "-")
    )
}

fn generate_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"]
}
"#
    .to_owned()
}

fn generate_readme(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {} Off-chain Builders\n\n", protocol.name));
    out.push_str("Generated by AikenFlow from the protocol IR.\n\n");
    out.push_str("These files define a structural transaction-builder adapter. Replace the structural types in `src/types.ts` with real Lucid, Mesh, Blaze, or project-local imports during integration.\n\n");
    out.push_str(
        "Repository outlines and agent-context files are not used as compiler semantics.\n\n",
    );
    out.push_str("## Layout\n\n");
    out.push_str("- `src/types.ts` contains structural SDK-compatible types.\n");
    out.push_str("- `src/index.ts` contains one builder function per transition.\n\n");
    out.push_str("## Asset Handling\n\n");
    out.push_str("- Explicit `outputs[].value` maps become `payToContract` asset maps.\n");
    out.push_str("- State-transition outputs without `value` carry assets from the consumed UTxOs when there is a consumed input to carry from.\n");
    out.push_str("- Creation outputs without `value` fail at runtime until the protocol spec declares explicit assets.\n\n");
    out.push_str("## Parameter Naming\n\n");
    out.push_str("- Self-transition outputs use `next<State>Address` and `next<State>Datum` parameters when input and output state names would otherwise collide.\n\n");
    out.push_str("## SDK Requirements\n\n");
    out.push_str(
        "- Transitions with reference inputs require transaction-builder `readFrom` support.\n",
    );
    out.push_str("- Transitions with mint or burn effects require transaction-builder `mintAssets` support.\n");
    out.push_str("- Missing required SDK methods fail at runtime instead of silently skipping protocol actions.\n\n");
    out.push_str("## Check\n\n```bash\nnpm run check\n```\n");
    out
}

fn generate_types(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str("// Generated by AikenFlow. Replace these structural types with real SDK imports when integrating.\n\n");
    out.push_str("export type Address = string;\n");
    out.push_str("export type AssetUnit = string;\n");
    out.push_str("export type Assets = Record<AssetUnit, bigint>;\n");
    out.push_str("export type DataValue = unknown;\n");
    out.push_str("export type SpendingValidator = unknown;\n");
    out.push_str("export type TxComplete = unknown;\n\n");
    out.push_str("export interface UTxO {\n");
    out.push_str("  txHash: string;\n");
    out.push_str("  outputIndex: number;\n");
    out.push_str("  assets?: Assets;\n");
    out.push_str("  datum?: DataValue;\n");
    out.push_str("}\n\n");
    out.push_str("export interface AikenFlowTxBuilder {\n");
    out.push_str("  collectFrom(utxos: UTxO[], redeemer?: DataValue): AikenFlowTxBuilder;\n");
    out.push_str("  readFrom?(utxos: UTxO[]): AikenFlowTxBuilder;\n");
    out.push_str("  payToContract(address: Address, datum: DataValue, assets: Assets): AikenFlowTxBuilder;\n");
    out.push_str("  attachSpendingValidator?(validator: SpendingValidator): AikenFlowTxBuilder;\n");
    out.push_str("  mintAssets?(assets: Assets, redeemer?: DataValue): AikenFlowTxBuilder;\n");
    out.push_str("  addSigner(address: Address): AikenFlowTxBuilder;\n");
    out.push_str("  validFrom(unixTimeMs: number | bigint): AikenFlowTxBuilder;\n");
    out.push_str("  validTo(unixTimeMs: number | bigint): AikenFlowTxBuilder;\n");
    out.push_str("  complete(): Promise<TxComplete>;\n");
    out.push_str("}\n\n");
    out.push_str("export interface AikenFlowLucid {\n");
    out.push_str("  newTx(): AikenFlowTxBuilder;\n");
    out.push_str("}\n\n");

    for state in &protocol.states {
        out.push_str(&generate_datum_interface(state));
    }

    out
}

fn generate_datum_interface(state: &StateDecl) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "export interface {}Datum {{\n",
        to_pascal_case(&state.name)
    ));

    if state.datum.is_empty() {
        out.push_str("  aikenflowUnit: bigint;\n");
    } else {
        for field in &state.datum {
            out.push_str(&format!(
                "  {}: {};\n",
                to_camel_case(&field.name),
                map_ts_type(&field.ty)
            ));
        }
    }

    out.push_str("}\n\n");
    out.push_str(&format!(
        "export function {}DatumToData(datum: {}Datum): DataValue {{\n",
        to_camel_case(&state.name),
        to_pascal_case(&state.name)
    ));
    out.push_str("  return {\n");
    out.push_str("    constructor: 0,\n");
    out.push_str("    fields: [\n");
    if state.datum.is_empty() {
        out.push_str("      datum.aikenflowUnit,\n");
    } else {
        for field in &state.datum {
            out.push_str(&format!("      datum.{},\n", to_camel_case(&field.name)));
        }
    }
    out.push_str("    ],\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out
}

fn generate_index(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by AikenFlow. These builders expose the protocol topology as code.\n",
    );
    out.push_str("import type { Address, AikenFlowLucid");
    if needs_required_tx_builder_helpers(protocol) {
        out.push_str(", AikenFlowTxBuilder");
    }
    out.push_str(", Assets, DataValue, SpendingValidator, TxComplete, UTxO");
    for state in &protocol.states {
        out.push_str(&format!(", {}Datum", to_pascal_case(&state.name)));
    }
    out.push_str(" } from \"./types.js\";\n");
    out.push_str("import { ");
    out.push_str(
        &protocol
            .states
            .iter()
            .map(|state| format!("{}DatumToData", to_camel_case(&state.name)))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str(" } from \"./types.js\";\n\n");
    out.push_str("export * from \"./types.js\";\n\n");
    out.push_str("function redeemerToData(name: string): DataValue {\n");
    out.push_str("  return { constructor: 0, fields: [name] };\n");
    out.push_str("}\n\n");
    out.push_str("function assetUnit(name: string): string {\n");
    out.push_str("  return name === \"ada\" ? \"lovelace\" : name;\n");
    out.push_str("}\n\n");
    out.push_str("function unresolvedAmount(expression: string): bigint {\n");
    out.push_str(
        "  throw new Error(`AikenFlow could not resolve amount expression: ${expression}`);\n",
    );
    out.push_str("}\n\n");

    if needs_asset_carry_helpers(protocol) {
        out.push_str("function assetsFromUtxos(utxos: UTxO[], label: string): Assets {\n");
        out.push_str("  if (utxos.length === 0) throw new Error(`AikenFlow cannot carry assets for ${label}: no UTxOs provided`);\n");
        out.push_str("  const assets: Assets = {};\n");
        out.push_str("  for (const utxo of utxos) {\n");
        out.push_str("    if (!utxo.assets) throw new Error(`AikenFlow cannot carry assets for ${label}: UTxO is missing assets`);\n");
        out.push_str("    for (const unit of Object.keys(utxo.assets)) {\n");
        out.push_str("      const amount = utxo.assets[unit];\n");
        out.push_str("      if (amount === undefined) continue;\n");
        out.push_str("      assets[unit] = (assets[unit] ?? 0n) + amount;\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
        out.push_str("  return assets;\n");
        out.push_str("}\n\n");
        out.push_str("function unresolvedAssets(reason: string): Assets {\n");
        out.push_str(
            "  throw new Error(`AikenFlow could not resolve output assets: ${reason}`);\n",
        );
        out.push_str("}\n\n");
    }

    if needs_reference_read_helpers(protocol) {
        out.push_str("function requireReadFrom(tx: AikenFlowTxBuilder, utxos: UTxO[], label: string): AikenFlowTxBuilder {\n");
        out.push_str("  if (!tx.readFrom) throw new Error(`AikenFlow transition ${label} requires readFrom support from the transaction builder`);\n");
        out.push_str("  return tx.readFrom(utxos);\n");
        out.push_str("}\n\n");
    }

    if needs_mint_assets_helpers(protocol) {
        out.push_str("function requireMintAssets(tx: AikenFlowTxBuilder, assets: Assets, redeemer: DataValue, label: string): AikenFlowTxBuilder {\n");
        out.push_str("  if (!tx.mintAssets) throw new Error(`AikenFlow transition ${label} requires mintAssets support from the transaction builder`);\n");
        out.push_str("  return tx.mintAssets(assets, redeemer);\n");
        out.push_str("}\n\n");
    }

    for (index, transition) in protocol.transitions.iter().enumerate() {
        out.push_str(&generate_transition_params(protocol, transition));
        out.push('\n');
        out.push_str(&generate_transition_builder(protocol, transition));
        if index + 1 < protocol.transitions.len() {
            out.push('\n');
        }
    }

    out
}

fn generate_transition_params(protocol: &Protocol, transition: &TransitionDecl) -> String {
    let interface_name = format!("{}Params", to_pascal_case(&transition.name));
    let default_datum_param = default_datum_param_name(transition);
    let mut fields = Vec::new();
    push_unique(&mut fields, "  lucid: AikenFlowLucid;".to_owned());

    for input in &transition.inputs {
        let field = input_binding_name(input);
        push_unique(&mut fields, format!("  {field}Utxos: UTxO[];"));
        push_unique(
            &mut fields,
            format!("  {field}Validator?: SpendingValidator;"),
        );
        if let Some(state) = protocol.state(&input.state) {
            push_unique(
                &mut fields,
                format!("  {field}Datum: {}Datum;", to_pascal_case(&state.name)),
            );
        }
    }

    for input in &transition.reference_inputs {
        let field = input_binding_name(input);
        push_unique(&mut fields, format!("  {field}ReferenceUtxos: UTxO[];"));
    }

    for output in &transition.outputs {
        let output_field = output_binding_name(transition, output);
        push_unique(&mut fields, format!("  {output_field}Address: Address;"));
        if let Some(state) = protocol.state(&output.state) {
            push_unique(
                &mut fields,
                format!(
                    "  {output_field}Datum: {}Datum;",
                    to_pascal_case(&state.name)
                ),
            );
        }
    }

    for variable in transition_variables(transition) {
        push_unique(&mut fields, format!("  {variable}: bigint;"));
    }

    for signer in signed_by_param_fields(transition, default_datum_param.as_deref()) {
        push_unique(&mut fields, format!("  {signer}: Address;"));
    }

    if transition
        .constraints
        .iter()
        .any(|constraint| matches!(constraint, Constraint::After(_)))
    {
        push_unique(&mut fields, "  validFrom?: number | bigint;".to_owned());
    }

    if transition
        .constraints
        .iter()
        .any(|constraint| matches!(constraint, Constraint::Before(_)))
    {
        push_unique(&mut fields, "  validTo?: number | bigint;".to_owned());
    }

    let mut out = String::new();
    out.push_str(&format!("export interface {interface_name} {{\n"));
    for field in fields {
        out.push_str(field.as_str());
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

fn generate_transition_builder(_protocol: &Protocol, transition: &TransitionDecl) -> String {
    let function_name = to_camel_case(&transition.name);
    let interface_name = format!("{}Params", to_pascal_case(&transition.name));
    let default_datum_param = default_datum_param_name(transition);
    let mut out = String::new();

    out.push_str(&format!(
        "export async function {function_name}(params: {interface_name}): Promise<TxComplete> {{\n"
    ));
    out.push_str("  let tx = params.lucid.newTx();\n\n");

    for input in &transition.inputs {
        let field = input_binding_name(input);
        out.push_str(&format!(
            "  if (params.{field}Validator && tx.attachSpendingValidator) tx = tx.attachSpendingValidator(params.{field}Validator);\n"
        ));
        out.push_str(&format!(
            "  tx = tx.collectFrom(params.{}Utxos, redeemerToData(\"{}\"));\n",
            field, transition.name
        ));
    }

    for input in &transition.reference_inputs {
        let field = input_binding_name(input);
        out.push_str(&format!(
            "  tx = requireReadFrom(tx, params.{field}ReferenceUtxos, {});\n",
            ts_string(&format!("{}.{}", transition.name, input.state))
        ));
    }

    for output in &transition.outputs {
        out.push_str(&generate_pay_to_contract_line(
            transition,
            output,
            default_datum_param.as_deref(),
        ));
    }

    for effect in &transition.mints {
        out.push_str(&format!(
            "  tx = requireMintAssets(tx, {{ [assetUnit({})]: {} }}, redeemerToData({}), {});\n",
            ts_string(&effect.asset),
            expression_to_ts(&effect.amount, default_datum_param.as_deref()),
            ts_string(&transition.name),
            ts_string(&format!("{}.mint.{}", transition.name, effect.asset))
        ));
    }

    for effect in &transition.burns {
        out.push_str(&format!(
            "  tx = requireMintAssets(tx, {{ [assetUnit({})]: {} }}, redeemerToData({}), {});\n",
            ts_string(&effect.asset),
            negate_bigint_expression(&expression_to_ts(
                &effect.amount,
                default_datum_param.as_deref()
            )),
            ts_string(&transition.name),
            ts_string(&format!("{}.burn.{}", transition.name, effect.asset))
        ));
    }

    for constraint in &transition.constraints {
        if let Constraint::SignedBy(expr) = constraint {
            out.push_str(&format!(
                "  tx = tx.addSigner({});\n",
                signer_expression_to_ts(expr, default_datum_param.as_deref())
            ));
        }
    }

    for constraint in &transition.constraints {
        match constraint {
            Constraint::After(expr) => {
                out.push_str(&format!(
                    "  tx = tx.validFrom(params.validFrom ?? {});\n",
                    expression_to_ts(expr, default_datum_param.as_deref())
                ));
            }
            Constraint::Before(expr) => {
                out.push_str(&format!(
                    "  tx = tx.validTo(params.validTo ?? {});\n",
                    expression_to_ts(expr, default_datum_param.as_deref())
                ));
            }
            _ => {}
        }
    }

    if transition.inputs.is_empty()
        && transition.outputs.is_empty()
        && transition.mints.is_empty()
        && transition.burns.is_empty()
    {
        out.push_str("  // This transition has no topology effects in the protocol spec yet.\n");
    }

    out.push_str("\n  return tx.complete();\n");
    out.push_str("}\n");
    out
}

fn generate_pay_to_contract_line(
    transition: &TransitionDecl,
    output: &StateOutput,
    default_datum_param: Option<&str>,
) -> String {
    let output_field = output_binding_name(transition, output);
    let address = format!("params.{output_field}Address");
    let datum = output_datum_to_data(output, &output_field, default_datum_param);
    let assets = output_assets_to_ts(transition, output, default_datum_param);

    format!("  tx = tx.payToContract({address}, {{ inline: {datum} }}, {assets} as Assets);\n")
}

fn output_assets_to_ts(
    transition: &TransitionDecl,
    output: &StateOutput,
    default_datum_param: Option<&str>,
) -> String {
    if output.value.is_empty() {
        return carried_assets_source(transition, output)
            .map(|input| {
                format!(
                    "assetsFromUtxos(params.{}Utxos, {})",
                    input_binding_name(input),
                    ts_string(&format!("{}.{}", transition.name, output.state))
                )
            })
            .unwrap_or_else(|| {
                format!(
                    "unresolvedAssets({})",
                    ts_string(&format!(
                        "transition `{}` output `{}` has no value assignment and no consumed input to carry assets",
                        transition.name, output.state
                    ))
                )
            });
    }

    let entries = output
        .value
        .iter()
        .map(|(asset, amount)| {
            format!(
                "[assetUnit({})]: {}",
                ts_string(asset),
                expression_to_ts(amount, default_datum_param)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("{{ {entries} }}")
}

fn carried_assets_source<'a>(
    transition: &'a TransitionDecl,
    output: &StateOutput,
) -> Option<&'a aikenflow_ir::StateInput> {
    transition
        .inputs
        .iter()
        .find(|input| input.state == output.state)
        .or_else(|| transition.inputs.first())
}

fn needs_asset_carry_helpers(protocol: &Protocol) -> bool {
    protocol
        .transitions
        .iter()
        .flat_map(|transition| &transition.outputs)
        .any(|output| output.value.is_empty())
}

fn needs_required_tx_builder_helpers(protocol: &Protocol) -> bool {
    needs_reference_read_helpers(protocol) || needs_mint_assets_helpers(protocol)
}

fn needs_reference_read_helpers(protocol: &Protocol) -> bool {
    protocol
        .transitions
        .iter()
        .any(|transition| !transition.reference_inputs.is_empty())
}

fn needs_mint_assets_helpers(protocol: &Protocol) -> bool {
    protocol
        .transitions
        .iter()
        .any(|transition| !transition.mints.is_empty() || !transition.burns.is_empty())
}

fn input_binding_name(input: &aikenflow_ir::StateInput) -> String {
    input
        .alias
        .as_deref()
        .map(to_camel_case)
        .filter(|alias| !alias.is_empty())
        .unwrap_or_else(|| to_camel_case(&input.state))
}

fn output_binding_name(transition: &TransitionDecl, output: &StateOutput) -> String {
    let base = to_camel_case(&output.state);
    if transition
        .inputs
        .iter()
        .any(|input| input_binding_name(input) == base)
    {
        format!("next{}", to_pascal_case(&output.state))
    } else {
        base
    }
}

fn default_datum_param_name(transition: &TransitionDecl) -> Option<String> {
    transition
        .inputs
        .first()
        .map(input_binding_name)
        .or_else(|| {
            transition
                .outputs
                .first()
                .map(|output| to_camel_case(&output.state))
        })
}

fn signed_by_param_fields(
    transition: &TransitionDecl,
    default_datum_param: Option<&str>,
) -> Vec<String> {
    let mut fields = Vec::new();

    for constraint in &transition.constraints {
        let Constraint::SignedBy(expr) = constraint else {
            continue;
        };
        if let Some(field) = signed_by_param_field(expr, default_datum_param) {
            push_unique(&mut fields, field);
        }
    }

    fields
}

fn signed_by_param_field(expr: &str, default_datum_param: Option<&str>) -> Option<String> {
    let trimmed = expr.trim();
    if let Some(variable) = trimmed.strip_prefix('$') {
        return Some(signer_param_name(variable));
    }

    if trimmed.strip_prefix("datum.").is_some() && default_datum_param.is_some() {
        return None;
    }

    Some("signer".to_owned())
}

fn signer_expression_to_ts(expr: &str, default_datum_param: Option<&str>) -> String {
    let trimmed = expr.trim();
    if let Some(variable) = trimmed.strip_prefix('$') {
        return format!("params.{}", signer_param_name(variable));
    }

    if let Some(field) = trimmed.strip_prefix("datum.") {
        if let Some(datum_param) = default_datum_param {
            return format!("params.{datum_param}Datum.{}", to_camel_case(field));
        }
    }

    "params.signer".to_owned()
}

fn signer_param_name(variable: &str) -> String {
    let base = to_camel_case(variable);
    if base == "signer" || base.ends_with("Signer") {
        base
    } else {
        format!("{base}Signer")
    }
}

fn output_datum_to_data(
    output: &StateOutput,
    output_param: &str,
    default_datum_param: Option<&str>,
) -> String {
    let state = to_camel_case(&output.state);
    let datum_to_data = format!("{state}DatumToData");

    if output.datum.is_empty() {
        return format!("{datum_to_data}(params.{output_param}Datum)");
    }

    let overrides = output
        .datum
        .iter()
        .map(|(field, value)| {
            format!(
                "{}: {}",
                to_camel_case(field),
                expression_to_ts(value, default_datum_param)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let datum_type = format!("{}Datum", to_pascal_case(&output.state));

    format!("{datum_to_data}({{ ...params.{output_param}Datum, {overrides} }} as {datum_type})")
}

fn transition_variables(transition: &TransitionDecl) -> BTreeSet<String> {
    let mut variables = BTreeSet::new();
    for output in &transition.outputs {
        for value in output.value.values().chain(output.datum.values()) {
            collect_variable(value, &mut variables);
        }
    }
    for effect in transition.mints.iter().chain(&transition.burns) {
        collect_variable(&effect.amount, &mut variables);
    }
    for constraint in &transition.constraints {
        match constraint {
            Constraint::SignedBy(_) => {}
            Constraint::Before(value)
            | Constraint::After(value)
            | Constraint::Positive(value)
            | Constraint::OutputExists(value)
            | Constraint::CustomAiken(value) => collect_variable(value, &mut variables),
            Constraint::ValuePreserved(Some(value)) => collect_variable(value, &mut variables),
            Constraint::DatumFieldEquals { field, value } => {
                collect_variable(field, &mut variables);
                collect_variable(value, &mut variables);
            }
            Constraint::ValuePreserved(None) | Constraint::Unknown { .. } => {}
        }
    }
    variables
}

fn push_unique(fields: &mut Vec<String>, field: String) {
    if !fields.contains(&field) {
        fields.push(field);
    }
}

fn collect_variable(expression: &str, variables: &mut BTreeSet<String>) {
    for part in expression.split(|character: char| {
        !character.is_ascii_alphanumeric() && character != '$' && character != '_'
    }) {
        if let Some(variable) = part.strip_prefix('$') {
            if !variable.is_empty() {
                variables.insert(to_camel_case(variable));
            }
        }
    }
}

fn expression_to_ts(expression: &str, default_datum_param: Option<&str>) -> String {
    let trimmed = expression.trim();
    if let Some(variable) = trimmed.strip_prefix('$') {
        return format!("params.{}", to_camel_case(variable));
    }
    if let Some(field) = trimmed.strip_prefix("datum.") {
        if let Some(datum_param) = default_datum_param {
            return format!("params.{datum_param}Datum.{}", to_camel_case(field));
        }
    }
    if trimmed.parse::<i64>().is_ok() {
        return format!("{trimmed}n");
    }
    format!("unresolvedAmount({})", ts_string(trimmed))
}

fn ts_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn negate_bigint_expression(expression: &str) -> String {
    if let Some(value) = expression.strip_prefix('-') {
        value.to_owned()
    } else if expression.ends_with('n')
        && expression
            .chars()
            .all(|c| c == 'n' || c == '-' || c.is_ascii_digit())
    {
        format!("-{expression}")
    } else {
        format!("-1n * ({expression})")
    }
}

fn map_ts_type(ty: &str) -> &'static str {
    match ty.trim() {
        "PubKeyHash" | "VerificationKeyHash" | "VKeyHash" | "Address" | "ByteArray" | "Bytes" => {
            "string"
        }
        "Lovelace" | "POSIXTime" | "Integer" | "Int" | "Natural" => "bigint",
        "Bool" | "Boolean" => "boolean",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use aikenflow_ir::{FieldDecl, StateInput, StateOutput};
    use std::collections::BTreeMap;

    #[test]
    fn generates_transition_function() {
        let protocol = Protocol {
            name: "SimpleVault".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![
                    FieldDecl {
                        name: "owner".to_owned(),
                        ty: "PubKeyHash".to_owned(),
                    },
                    FieldDecl {
                        name: "count".to_owned(),
                        ty: "Int".to_owned(),
                    },
                ],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Withdraw".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![
                    Constraint::SignedBy("datum.owner".to_owned()),
                    Constraint::After("datum.count".to_owned()),
                ],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("export async function withdraw"));
        assert!(index.contains("lockedValidator?: SpendingValidator"));
        assert!(index.contains("tx.attachSpendingValidator(params.lockedValidator)"));
        assert!(index.contains("tx.collectFrom(params.lockedUtxos"));
        assert!(index.contains("tx.addSigner(params.lockedDatum.owner)"));
        assert!(BTreeMap::<String, String>::new().is_empty());
        assert!(std::mem::size_of::<StateOutput>() > 0);
    }

    #[test]
    fn dollar_signers_get_named_address_parameters() {
        let protocol = Protocol {
            name: "MintAuth".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Create".to_owned(),
                inputs: vec![],
                reference_inputs: vec![],
                outputs: vec![StateOutput {
                    state: "Locked".to_owned(),
                    value: BTreeMap::new(),
                    datum: BTreeMap::new(),
                }],
                mints: vec![],
                burns: vec![],
                constraints: vec![
                    Constraint::SignedBy("$owner".to_owned()),
                    Constraint::SignedBy("$operator_signer".to_owned()),
                ],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("ownerSigner: Address;"));
        assert!(index.contains("operatorSigner: Address;"));
        assert!(index.contains("tx.addSigner(params.ownerSigner);"));
        assert!(index.contains("tx.addSigner(params.operatorSigner);"));
    }

    #[test]
    fn unresolved_amounts_are_explicit_runtime_errors() {
        assert_eq!(
            expression_to_ts("datum.unknown", None),
            "unresolvedAmount(\"datum.unknown\")"
        );
    }

    #[test]
    fn burns_are_represented_as_negative_mint_assets() {
        let protocol = Protocol {
            name: "Burnable".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "Burn".to_owned(),
                inputs: vec![],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![aikenflow_ir::AssetEffect {
                    policy: "policy".to_owned(),
                    asset: "token".to_owned(),
                    amount: "$amount".to_owned(),
                }],
                constraints: vec![],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("function requireMintAssets"));
        assert!(index
            .contains("requireMintAssets(tx, { [assetUnit(\"token\")]: -1n * (params.amount) }"));
    }

    #[test]
    fn output_datum_overrides_are_applied_to_builder_datum() {
        let protocol = Protocol {
            name: "Counter".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![
                    FieldDecl {
                        name: "owner".to_owned(),
                        ty: "PubKeyHash".to_owned(),
                    },
                    FieldDecl {
                        name: "count".to_owned(),
                        ty: "Int".to_owned(),
                    },
                ],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Increment".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![StateOutput {
                    state: "Locked".to_owned(),
                    value: BTreeMap::new(),
                    datum: [("count".to_owned(), "$next_count".to_owned())].into(),
                }],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::SignedBy("datum.owner".to_owned())],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("nextLockedAddress: Address;"));
        assert!(index.contains("nextLockedDatum: LockedDatum;"));
        assert!(index.contains("nextCount: bigint;"));
        assert!(index.contains("lockedDatumToData({ ...params.nextLockedDatum, count: params.nextCount } as LockedDatum)"));
        assert!(index.contains("assetsFromUtxos(params.lockedUtxos"));
    }

    #[test]
    fn input_aliases_control_builder_parameter_names() {
        let protocol = Protocol {
            name: "Swap".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![
                    FieldDecl {
                        name: "owner".to_owned(),
                        ty: "PubKeyHash".to_owned(),
                    },
                    FieldDecl {
                        name: "count".to_owned(),
                        ty: "Int".to_owned(),
                    },
                ],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Match".to_owned(),
                inputs: vec![
                    StateInput {
                        state: "Locked".to_owned(),
                        alias: Some("left".to_owned()),
                    },
                    StateInput {
                        state: "Locked".to_owned(),
                        alias: Some("right".to_owned()),
                    },
                ],
                reference_inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: Some("oracle".to_owned()),
                }],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![
                    Constraint::SignedBy("datum.owner".to_owned()),
                    Constraint::After("datum.count".to_owned()),
                ],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("leftUtxos: UTxO[];"));
        assert!(index.contains("rightUtxos: UTxO[];"));
        assert!(index.contains("oracleReferenceUtxos: UTxO[];"));
        assert!(index.contains("tx.collectFrom(params.leftUtxos"));
        assert!(index.contains("tx.collectFrom(params.rightUtxos"));
        assert!(index.contains("function requireReadFrom"));
        assert!(index
            .contains("tx = requireReadFrom(tx, params.oracleReferenceUtxos, \"Match.Locked\")"));
        assert!(index.contains("params.leftDatum.count"));
    }

    #[test]
    fn empty_creation_output_assets_are_explicit_runtime_errors() {
        let protocol = Protocol {
            name: "Starter".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Open".to_owned(),
                datum: vec![],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Create".to_owned(),
                inputs: vec![],
                reference_inputs: vec![],
                outputs: vec![StateOutput {
                    state: "Open".to_owned(),
                    value: BTreeMap::new(),
                    datum: BTreeMap::new(),
                }],
                mints: vec![],
                burns: vec![],
                constraints: vec![],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let files = generate(&protocol);
        let index = files
            .files
            .iter()
            .find(|file| file.path == "src/index.ts")
            .expect("index")
            .content
            .as_str();

        assert!(index.contains("function unresolvedAssets"));
        assert!(index.contains(
            "unresolvedAssets(\"transition `Create` output `Open` has no value assignment"
        ));
    }

    #[test]
    fn empty_datum_interface_serializes_unit_marker() {
        let state = StateDecl {
            name: "Open".to_owned(),
            datum: vec![],
            script: None,
            terminal: false,
        };

        let types = generate_datum_interface(&state);

        assert!(types.contains("aikenflowUnit: bigint;"));
        assert!(types.contains("datum.aikenflowUnit"));
        assert!(!types.contains("temporaryField"));
    }
}
