use aikenflow_ir::{
    to_snake_case, Constraint, GeneratedFiles, InvariantDecl, Protocol, TransitionDecl,
};
use serde::Serialize;

pub fn generate(protocol: &Protocol) -> GeneratedFiles {
    let mut files = GeneratedFiles::default();
    files.push("README.md", generate_readme(protocol));
    files.push("state-graph.mmd", generate_state_graph(protocol));
    files.push("topology.json", generate_topology_json(protocol));
    files.push("coverage.json", generate_coverage_json(protocol));
    files.push("invariant-matrix.md", generate_invariant_matrix(protocol));
    files.push(
        "adversarial-cases.md",
        generate_adversarial_cases_markdown(protocol),
    );
    files.push(
        "tests/adversarial.spec.ts",
        generate_adversarial_test_stubs(protocol),
    );
    files.push("AUDIT.md", generate_audit_report(protocol));
    files
}

pub fn generate_readme(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {} Assurance Artefacts\n\n", protocol.name));
    out.push_str("Generated by AikenFlow from the protocol IR.\n\n");
    out.push_str("These artefacts support review, testing, and audit preparation. They are not formal proofs and do not use repository outlines or agent-context files as protocol semantics.\n\n");
    out.push_str("## Files\n\n");
    out.push_str("- `state-graph.mmd`: Mermaid state machine graph.\n");
    out.push_str("- `topology.json`: Machine-readable transition topology.\n");
    out.push_str(
        "- `coverage.json`: Machine-readable constraint and invariant coverage summary.\n",
    );
    out.push_str("- `invariant-matrix.md`: Invariant-to-transition review matrix.\n");
    out.push_str("- `adversarial-cases.md`: Generated negative-case checklist.\n");
    out.push_str(
        "- `tests/adversarial.spec.ts`: TypeScript test stubs for emulator integration.\n",
    );
    out.push_str("- `AUDIT.md`: Human-readable protocol audit artefact.\n");
    out
}

pub fn generate_state_graph(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str("stateDiagram-v2\n");

    for transition in &protocol.transitions {
        if transition.inputs.is_empty() {
            if transition.outputs.is_empty() {
                out.push_str(&format!("    [*] --> [*]: {}\n", transition.name));
            } else {
                for output in &transition.outputs {
                    out.push_str(&format!(
                        "    [*] --> {}: {}\n",
                        output.state, transition.name
                    ));
                }
            }
            continue;
        }

        if transition.outputs.is_empty() {
            for input in &transition.inputs {
                out.push_str(&format!(
                    "    {} --> [*]: {}\n",
                    input.state, transition.name
                ));
            }
            continue;
        }

        for input in &transition.inputs {
            for output in &transition.outputs {
                out.push_str(&format!(
                    "    {} --> {}: {}\n",
                    input.state, output.state, transition.name
                ));
            }
        }
    }

    out
}

pub fn generate_topology_json(protocol: &Protocol) -> String {
    let mut json =
        serde_json::to_string_pretty(&protocol.topology()).expect("topology is serializable");
    json.push('\n');
    json
}

pub fn generate_coverage_json(protocol: &Protocol) -> String {
    let report = CoverageReport {
        formal_proof_status: "not_formally_proven",
        constraints: protocol
            .transitions
            .iter()
            .flat_map(|transition| {
                transition.constraints.iter().map(move |constraint| {
                    let (negative_case, compiler_coverage) =
                        constraint_coverage(protocol, transition, constraint);
                    ConstraintCoverageJson {
                        transition: transition.name.clone(),
                        constraint: constraint.label(),
                        negative_case: markdown_code_to_plain(negative_case),
                        compiler_coverage,
                    }
                })
            })
            .collect(),
        invariants: protocol
            .invariants
            .iter()
            .map(|invariant| {
                let transitions = transitions_for_invariant(protocol, invariant);
                let generated_negative_cases = transitions
                    .iter()
                    .map(|transition| adversarial_cases_for_transition(transition).len())
                    .sum::<usize>();
                InvariantCoverageJson {
                    invariant: invariant.name.clone(),
                    expression: invariant.expression.clone(),
                    transitions_covered: transitions
                        .iter()
                        .map(|transition| transition.name.clone())
                        .collect(),
                    generated_negative_cases,
                    test_coverage_status: invariant_test_coverage_status(protocol, invariant),
                    formal_status: "not_formally_proven",
                }
            })
            .collect(),
    };

    let mut json = serde_json::to_string_pretty(&report).expect("coverage report is serializable");
    json.push('\n');
    json
}

#[derive(Debug, Serialize)]
struct CoverageReport<'a> {
    formal_proof_status: &'a str,
    constraints: Vec<ConstraintCoverageJson<'a>>,
    invariants: Vec<InvariantCoverageJson<'a>>,
}

#[derive(Debug, Serialize)]
struct ConstraintCoverageJson<'a> {
    transition: String,
    constraint: String,
    negative_case: String,
    compiler_coverage: &'a str,
}

#[derive(Debug, Serialize)]
struct InvariantCoverageJson<'a> {
    invariant: String,
    expression: String,
    transitions_covered: Vec<String>,
    generated_negative_cases: usize,
    test_coverage_status: &'a str,
    formal_status: &'a str,
}

pub fn generate_invariant_matrix(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str("# Invariant Matrix\n\n");
    out.push_str("| Invariant | Transitions Covered | Generated Negative Cases | Status |\n");
    out.push_str("|---|---|---:|---|\n");

    if protocol.invariants.is_empty() {
        out.push_str("| _none declared_ | _n/a_ | 0 | missing |\n");
        return out;
    }

    for invariant in &protocol.invariants {
        let transitions = transitions_for_invariant(protocol, invariant);
        let generated_cases = transitions
            .iter()
            .map(|transition| adversarial_cases_for_transition(transition).len())
            .sum::<usize>();
        let status = if transitions.is_empty() {
            "not mapped"
        } else {
            "scaffolded"
        };
        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            invariant.name,
            if transitions.is_empty() {
                "_not mapped_".to_owned()
            } else {
                transitions
                    .iter()
                    .map(|transition| transition.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            },
            generated_cases,
            status
        ));
    }

    out
}

pub fn generate_adversarial_cases_markdown(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str("# Generated Adversarial Cases\n\n");

    for transition in &protocol.transitions {
        out.push_str(&format!("## {}\n\n", transition.name));
        let cases = adversarial_cases_for_transition(transition);
        if cases.is_empty() {
            out.push_str(
                "- No negative cases generated yet. Add constraints to the transition.\n\n",
            );
            continue;
        }
        for case in cases {
            out.push_str(&format!("- `{}`: {}\n", case.id, case.description));
        }
        out.push('\n');
    }

    if out.ends_with("\n\n") {
        out.pop();
    }
    out
}

pub fn generate_adversarial_test_stubs(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by AikenFlow. These cases fail until connected to a local Lucid/Yaci fixture.\n",
    );
    out.push_str("import { describe, it } from \"node:test\";\n");
    out.push_str("import assert from \"node:assert/strict\";\n\n");
    out.push_str(&format!(
        "describe(\"{} adversarial cases\", () => {{\n",
        protocol.name
    ));

    for transition in &protocol.transitions {
        for case in adversarial_cases_for_transition(transition) {
            out.push_str(&format!(
                "  it(\"{} rejects {}\", () => {{\n",
                transition.name, case.id
            ));
            out.push_str(
                "    assert.fail(\"AikenFlow generated this adversarial case, but no local emulator fixture is wired yet.\");\n",
            );
            out.push_str("  });\n");
        }
    }

    out.push_str("});\n");
    out
}

pub fn generate_audit_report(protocol: &Protocol) -> String {
    let mut out = String::new();
    out.push_str("# Protocol Audit Artefact\n\n");
    out.push_str("Generated by AikenFlow from the protocol specification.\n\n");
    out.push_str("Assurance artefacts are generated from AikenFlow IR. They are review and test scaffolds, not formal proofs. Repository outlines and agent-context files are not used as protocol semantics.\n\n");
    out.push_str("## Protocol Summary\n\n");
    out.push_str(&format!("- Protocol: `{}`\n", protocol.name));
    if let Some(description) = &protocol.description {
        out.push_str(&format!("- Description: {}\n", description));
    }
    out.push_str(&format!("- States: {}\n", protocol.states.len()));
    out.push_str(&format!("- Transitions: {}\n", protocol.transitions.len()));
    out.push_str(&format!("- Invariants: {}\n\n", protocol.invariants.len()));

    out.push_str("## State Machine\n\n");
    out.push_str("```mermaid\n");
    out.push_str(&generate_state_graph(protocol));
    out.push_str("```\n\n");

    out.push_str("## Assets\n\n");
    if protocol.assets.is_empty() {
        out.push_str("_No assets declared._\n\n");
    } else {
        out.push_str("| Name | Kind | Policy |\n|---|---|---|\n");
        for asset in &protocol.assets {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                asset.name,
                asset.kind,
                asset.policy.as_deref().unwrap_or("_n/a_")
            ));
        }
        out.push('\n');
    }

    out.push_str("## Datum Schemas\n\n");
    for state in &protocol.states {
        out.push_str(&format!("### {}\n\n", state.name));
        if state.datum.is_empty() {
            out.push_str("_No datum fields declared._\n\n");
            continue;
        }
        out.push_str("| Field | Type |\n|---|---|\n");
        for field in &state.datum {
            out.push_str(&format!("| `{}` | `{}` |\n", field.name, field.ty));
        }
        out.push('\n');
    }

    out.push_str("## Redeemer Schemas\n\n");
    for state in &protocol.states {
        let redeemers = protocol
            .transitions_consuming_state(&state.name)
            .map(|transition| format!("`{}`", transition.name))
            .collect::<Vec<_>>();
        if redeemers.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "- `{}` accepts {}\n",
            state.name,
            redeemers.join(", ")
        ));
    }
    out.push('\n');

    out.push_str("## Transition Table\n\n");
    out.push_str("| Transition | Consumes | References | Produces | Constraints |\n");
    out.push_str("|---|---|---|---|---|\n");
    for transition in &protocol.transitions {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            transition.name,
            join_or_dash(transition.inputs.iter().map(|input| input.state.as_str())),
            join_or_dash(
                transition
                    .reference_inputs
                    .iter()
                    .map(|input| input.state.as_str())
            ),
            join_or_dash(
                transition
                    .outputs
                    .iter()
                    .map(|output| output.state.as_str())
            ),
            join_or_dash(
                transition
                    .constraints
                    .iter()
                    .map(|constraint| constraint.label())
            )
        ));
    }
    out.push('\n');

    out.push_str("## Constraint Coverage\n\n");
    out.push_str("| Transition | Constraint | Generated Negative Case | Compiler Coverage |\n");
    out.push_str("|---|---|---|---|\n");
    for transition in &protocol.transitions {
        if transition.constraints.is_empty() {
            out.push_str(&format!(
                "| `{}` | _none_ | _none_ | _manual review_ |\n",
                transition.name
            ));
            continue;
        }
        for constraint in &transition.constraints {
            let (negative_case, coverage) = constraint_coverage(protocol, transition, constraint);
            out.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                transition.name,
                markdown_cell(&constraint.label()),
                negative_case,
                coverage
            ));
        }
    }
    out.push('\n');

    out.push_str("## Invariants\n\n");
    if protocol.invariants.is_empty() {
        out.push_str("_No invariants declared._\n\n");
    } else {
        out.push_str("These invariants are **not formally proven** by AikenFlow. They are review targets with generated test scaffolding where matching transitions can be identified.\n\n");
        out.push_str("| Invariant | Expression | Formal Status | Generated Test Coverage |\n");
        out.push_str("|---|---|---|---|\n");
        for invariant in &protocol.invariants {
            out.push_str(&format!(
                "| `{}` | `{}` | not formally proven | {} |\n",
                invariant.name,
                markdown_cell(&invariant.expression),
                invariant_test_coverage(protocol, invariant)
            ));
        }
        out.push('\n');
    }

    out.push_str("## Threat Model\n\n");
    out.push_str("- Missing required signatures.\n");
    out.push_str("- Premature or expired validity intervals.\n");
    out.push_str("- Mutated datum fields across state transitions.\n");
    out.push_str("- Missing required outputs after consuming state UTxOs.\n");
    out.push_str("- Asset conservation failures or incorrect mint/burn amounts.\n\n");

    out.push_str("## Generated Adversarial Cases\n\n");
    for transition in &protocol.transitions {
        let cases = adversarial_cases_for_transition(transition);
        out.push_str(&format!(
            "- `{}`: {} case(s)\n",
            transition.name,
            cases.len()
        ));
    }
    out.push('\n');

    out.push_str("## Assumptions\n\n");
    out.push_str("- Generated validators are readable scaffolds and must be reviewed before production deployment.\n");
    out.push_str("- Generated TypeScript builders expose topology and require integration with a concrete Lucid/Yaci setup.\n");
    out.push_str("- The MVP supports script spending, simple outputs, signatures, validity windows, and mint/burn summaries.\n\n");

    out.push_str("## Known Limitations\n\n");
    out.push_str("- No formal proof backend is included.\n");
    out.push_str(
        "- Multi-validator protocol coordination is represented but not fully verified.\n",
    );
    out.push_str("- Custom Aiken constraints are preserved as code snippets only when they are valid expressions.\n");
    out.push_str("- Cost profiling requires running `aiken build` and local transaction evaluation outside this crate.\n\n");

    out.push_str("## Cost Profile\n\n");
    out.push_str("_Not measured. Run Aiken and local emulator tooling after generation._\n");

    out
}

#[derive(Debug, Clone)]
struct AdversarialCase {
    id: String,
    description: String,
}

fn adversarial_cases_for_transition(transition: &TransitionDecl) -> Vec<AdversarialCase> {
    let mut cases = Vec::new();
    for constraint in &transition.constraints {
        match constraint {
            Constraint::SignedBy(signer) => cases.push(AdversarialCase {
                id: "missing_signature".to_owned(),
                description: format!("Omit required signer `{signer}`."),
            }),
            Constraint::After(point) => cases.push(AdversarialCase {
                id: "premature_validity_interval".to_owned(),
                description: format!("Set validity interval before `{point}`."),
            }),
            Constraint::Before(point) => cases.push(AdversarialCase {
                id: "expired_validity_interval".to_owned(),
                description: format!("Set validity interval after `{point}`."),
            }),
            Constraint::Positive(value) => cases.push(AdversarialCase {
                id: "non_positive_value".to_owned(),
                description: format!("Use zero or negative value for `{value}`."),
            }),
            Constraint::ValuePreserved(value) => cases.push(AdversarialCase {
                id: "value_not_preserved".to_owned(),
                description: format!(
                    "Construct outputs that fail to preserve `{}`.",
                    value.as_deref().unwrap_or("declared value")
                ),
            }),
            Constraint::OutputExists(output) => cases.push(AdversarialCase {
                id: "missing_required_output".to_owned(),
                description: format!("Omit required output `{output}`."),
            }),
            Constraint::DatumFieldEquals { field, value } => cases.push(AdversarialCase {
                id: "mutated_datum_field".to_owned(),
                description: format!("Set `{field}` to a value other than `{value}`."),
            }),
            Constraint::CustomAiken(_) => cases.push(AdversarialCase {
                id: "custom_constraint_violation".to_owned(),
                description: "Build a transaction that violates the custom constraint.".to_owned(),
            }),
            Constraint::Unknown { name, .. } => cases.push(AdversarialCase {
                id: "unknown_constraint_violation".to_owned(),
                description: format!(
                    "Build a transaction that violates unknown constraint `{name}`."
                ),
            }),
        }
    }
    cases
}

fn constraint_coverage(
    protocol: &Protocol,
    transition: &TransitionDecl,
    constraint: &Constraint,
) -> (&'static str, &'static str) {
    if transition.inputs.is_empty() {
        return match constraint {
            Constraint::SignedBy(_) => (
                "`missing_signature`",
                "off-chain signer parameter and test scaffold; no generated validator branch",
            ),
            Constraint::After(_) => (
                "`premature_validity_interval`",
                "off-chain validity parameter and test scaffold; no generated validator branch",
            ),
            Constraint::Before(_) => (
                "`expired_validity_interval`",
                "off-chain validity parameter and test scaffold; no generated validator branch",
            ),
            Constraint::Positive(_) => (
                "`non_positive_value`",
                "test scaffold and manual review only; no generated validator branch",
            ),
            Constraint::ValuePreserved(_) => (
                "`value_not_preserved`",
                "assurance report and test scaffold only",
            ),
            Constraint::OutputExists(_) => (
                "`missing_required_output`",
                "assurance report and test scaffold only",
            ),
            Constraint::DatumFieldEquals { .. } => (
                "`mutated_datum_field`",
                "test scaffold and manual review only; no generated validator branch",
            ),
            Constraint::CustomAiken(_) => (
                "`custom_constraint_violation`",
                "custom expression requires manual implementation; no generated validator branch",
            ),
            Constraint::Unknown { .. } => (
                "`unknown_constraint_violation`",
                "report-only warning and manual implementation required",
            ),
        };
    }

    if !has_generated_validator_coverage(protocol, transition, constraint) {
        return match constraint {
            Constraint::SignedBy(_) => (
                "`missing_signature`",
                "test scaffold and manual review only; expression is not covered by generated validator checks",
            ),
            Constraint::After(_) => (
                "`premature_validity_interval`",
                "test scaffold and manual review only; expression is not covered by generated validator checks",
            ),
            Constraint::Before(_) => (
                "`expired_validity_interval`",
                "test scaffold and manual review only; expression is not covered by generated validator checks",
            ),
            Constraint::Positive(_) => (
                "`non_positive_value`",
                "test scaffold and manual review only; expression is not covered by generated validator checks",
            ),
            Constraint::DatumFieldEquals { .. } => (
                "`mutated_datum_field`",
                "test scaffold and manual review only; expression is not covered by generated validator checks",
            ),
            Constraint::ValuePreserved(_) => (
                "`value_not_preserved`",
                "assurance report and test scaffold only",
            ),
            Constraint::OutputExists(_) => (
                "`missing_required_output`",
                "assurance report and test scaffold only",
            ),
            Constraint::CustomAiken(_) => (
                "`custom_constraint_violation`",
                "custom expression passthrough with manual review",
            ),
            Constraint::Unknown { .. } => (
                "`unknown_constraint_violation`",
                "report-only warning and manual implementation required",
            ),
        };
    }

    match constraint {
        Constraint::SignedBy(_) => (
            "`missing_signature`",
            "generated validator check and test scaffold",
        ),
        Constraint::After(_) => (
            "`premature_validity_interval`",
            "generated validator check and test scaffold",
        ),
        Constraint::Before(_) => (
            "`expired_validity_interval`",
            "generated validator check and test scaffold",
        ),
        Constraint::Positive(_) => (
            "`non_positive_value`",
            "generated validator check and test scaffold",
        ),
        Constraint::ValuePreserved(_) => (
            "`value_not_preserved`",
            "assurance report and test scaffold only",
        ),
        Constraint::OutputExists(_) => (
            "`missing_required_output`",
            "assurance report and test scaffold only",
        ),
        Constraint::DatumFieldEquals { .. } => (
            "`mutated_datum_field`",
            "generated validator check and test scaffold",
        ),
        Constraint::CustomAiken(_) => (
            "`custom_constraint_violation`",
            "custom expression passthrough with manual review",
        ),
        Constraint::Unknown { .. } => (
            "`unknown_constraint_violation`",
            "report-only warning and manual implementation required",
        ),
    }
}

fn has_generated_validator_coverage(
    protocol: &Protocol,
    transition: &TransitionDecl,
    constraint: &Constraint,
) -> bool {
    if transition.inputs.is_empty() {
        return false;
    }

    match constraint {
        Constraint::SignedBy(expr)
        | Constraint::Before(expr)
        | Constraint::After(expr)
        | Constraint::Positive(expr) => transition.inputs.iter().any(|input| {
            protocol
                .state(&input.state)
                .is_some_and(|state| datum_expr_resolves(state, expr))
        }),
        Constraint::DatumFieldEquals { field, value } => transition.inputs.iter().any(|input| {
            protocol.state(&input.state).is_some_and(|state| {
                datum_expr_resolves(state, field)
                    && (datum_expr_resolves(state, value) || literal_like(value))
            })
        }),
        Constraint::CustomAiken(_) => true,
        Constraint::ValuePreserved(_)
        | Constraint::OutputExists(_)
        | Constraint::Unknown { .. } => false,
    }
}

fn datum_expr_resolves(state: &aikenflow_ir::StateDecl, expr: &str) -> bool {
    let trimmed = expr.trim().trim_matches('"');
    let candidate = trimmed
        .strip_prefix("datum.")
        .or_else(|| trimmed.strip_prefix('$'))
        .unwrap_or(trimmed);

    state.datum.iter().any(|field| field.name == candidate)
}

fn literal_like(value: &str) -> bool {
    let trimmed = value.trim();
    trimmed.parse::<i64>().is_ok() || matches!(trimmed, "True" | "False")
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|")
}

fn markdown_code_to_plain(value: &str) -> String {
    value.trim_matches('`').to_owned()
}

fn transitions_for_invariant<'a>(
    protocol: &'a Protocol,
    invariant: &InvariantDecl,
) -> Vec<&'a TransitionDecl> {
    let expression = invariant.expression.to_lowercase();
    protocol
        .transitions
        .iter()
        .filter(|transition| mentions_transition(&expression, &transition.name))
        .collect::<Vec<_>>()
}

fn mentions_transition(lowercase_expression: &str, transition_name: &str) -> bool {
    lowercase_expression.contains(&format!("transition.{}", transition_name.to_lowercase()))
}

fn invariant_test_coverage(protocol: &Protocol, invariant: &InvariantDecl) -> String {
    let transitions = transitions_for_invariant(protocol, invariant);
    if transitions.is_empty() {
        return "_not mapped_".to_owned();
    }

    let cases = transitions
        .iter()
        .map(|transition| adversarial_cases_for_transition(transition).len())
        .sum::<usize>();

    if cases == 0 {
        "review-only; no generated negative cases".to_owned()
    } else {
        format!("partial; {cases} generated negative case(s)")
    }
}

fn invariant_test_coverage_status(protocol: &Protocol, invariant: &InvariantDecl) -> &'static str {
    let transitions = transitions_for_invariant(protocol, invariant);
    if transitions.is_empty() {
        return "not_mapped";
    }

    let cases = transitions
        .iter()
        .map(|transition| adversarial_cases_for_transition(transition).len())
        .sum::<usize>();

    if cases == 0 {
        "review_only"
    } else {
        "partial"
    }
}

fn join_or_dash<I, S>(items: I) -> String
where
    I: IntoIterator<Item = S>,
    S: ToString,
{
    let values = items
        .into_iter()
        .map(|item| {
            let text = item.to_string();
            if text.starts_with('`') {
                text
            } else {
                format!("`{}`", text)
            }
        })
        .collect::<Vec<_>>();

    if values.is_empty() {
        "_none_".to_owned()
    } else {
        values.join(", ")
    }
}

#[allow(dead_code)]
fn artifact_stem(protocol: &Protocol) -> String {
    to_snake_case(&protocol.name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use aikenflow_ir::{Constraint, FieldDecl, StateDecl, StateInput, TransitionDecl};

    #[test]
    fn state_graph_handles_terminal_transition() {
        let protocol = Protocol {
            name: "SimpleVault".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "Withdraw".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::SignedBy("datum.owner".to_owned())],
                effects: vec![],
            }],
            invariants: vec![],
        };

        assert!(generate_state_graph(&protocol).contains("Locked --> [*]: Withdraw"));
    }

    #[test]
    fn audit_marks_unknown_constraints_as_manual_coverage() {
        let protocol = Protocol {
            name: "ManualCoverage".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "DoThing".to_owned(),
                inputs: vec![],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::Unknown {
                    name: "requires_oracle".to_owned(),
                    value: Some("oracle_price".to_owned()),
                }],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let audit = generate_audit_report(&protocol);

        assert!(audit.contains("unknown_constraint_violation"));
        assert!(audit.contains("manual implementation required"));
    }

    #[test]
    fn audit_does_not_claim_validator_coverage_for_creation_transitions() {
        let protocol = Protocol {
            name: "CreationCoverage".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "Create".to_owned(),
                inputs: vec![],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![
                    Constraint::SignedBy("$owner".to_owned()),
                    Constraint::Positive("$amount".to_owned()),
                ],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let audit = generate_audit_report(&protocol);

        assert!(audit.contains("off-chain signer parameter and test scaffold"));
        assert!(audit.contains("test scaffold and manual review only"));
        assert!(!audit.contains(
            "| `Create` | `signed_by($owner)` | `missing_signature` | generated validator check"
        ));
    }

    #[test]
    fn audit_does_not_claim_validator_coverage_for_unresolved_input_constraints() {
        let protocol = Protocol {
            name: "UnresolvedCoverage".to_owned(),
            description: None,
            assets: vec![],
            states: vec![StateDecl {
                name: "Locked".to_owned(),
                datum: vec![FieldDecl {
                    name: "owner".to_owned(),
                    ty: "PubKeyHash".to_owned(),
                }],
                script: None,
                terminal: false,
            }],
            transitions: vec![TransitionDecl {
                name: "Spend".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::Positive("$amount".to_owned())],
                effects: vec![],
            }],
            invariants: vec![],
        };

        let audit = generate_audit_report(&protocol);

        assert!(audit.contains("expression is not covered by generated validator checks"));
        assert!(!audit.contains(
            "| `Spend` | `positive($amount)` | `non_positive_value` | generated validator check"
        ));
    }

    #[test]
    fn audit_marks_invariants_as_not_formally_proven() {
        let protocol = Protocol {
            name: "InvariantCoverage".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "Spend".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::SignedBy("datum.owner".to_owned())],
                effects: vec![],
            }],
            invariants: vec![aikenflow_ir::InvariantDecl {
                name: "spend_requires_owner".to_owned(),
                expression: "transition.Spend requires signature(datum.owner)".to_owned(),
            }],
        };

        let audit = generate_audit_report(&protocol);

        assert!(audit.contains("not formally proven"));
        assert!(audit.contains("partial; 1 generated negative case(s)"));
    }

    #[test]
    fn generic_invariants_are_not_mapped_to_every_transition() {
        let protocol = Protocol {
            name: "InvariantCoverage".to_owned(),
            description: None,
            assets: vec![],
            states: vec![],
            transitions: vec![TransitionDecl {
                name: "Spend".to_owned(),
                inputs: vec![StateInput {
                    state: "Locked".to_owned(),
                    alias: None,
                }],
                reference_inputs: vec![],
                outputs: vec![],
                mints: vec![],
                burns: vec![],
                constraints: vec![Constraint::SignedBy("datum.owner".to_owned())],
                effects: vec![],
            }],
            invariants: vec![aikenflow_ir::InvariantDecl {
                name: "global_value_conservation".to_owned(),
                expression: "total value is preserved".to_owned(),
            }],
        };

        let matrix = generate_invariant_matrix(&protocol);
        let audit = generate_audit_report(&protocol);

        assert!(matrix.contains("| `global_value_conservation` | _not mapped_ | 0 | not mapped |"));
        assert!(audit.contains("| `global_value_conservation` | `total value is preserved` | not formally proven | _not mapped_ |"));
    }
}
