// Generated by AikenFlow. Replace these structural types with real SDK imports when integrating.

export type Address = string;
export type AssetUnit = string;
export type Assets = Record<AssetUnit, bigint>;
export type DataValue = unknown;
export type SpendingValidator = unknown;
export type TxComplete = unknown;

export interface UTxO {
  txHash: string;
  outputIndex: number;
  assets?: Assets;
  datum?: DataValue;
}

export interface AikenFlowTxBuilder {
  collectFrom(utxos: UTxO[], redeemer?: DataValue): AikenFlowTxBuilder;
  readFrom?(utxos: UTxO[]): AikenFlowTxBuilder;
  payToContract(address: Address, datum: DataValue, assets: Assets): AikenFlowTxBuilder;
  attachSpendingValidator?(validator: SpendingValidator): AikenFlowTxBuilder;
  mintAssets?(assets: Assets, redeemer?: DataValue): AikenFlowTxBuilder;
  addSigner(address: Address): AikenFlowTxBuilder;
  validFrom(unixTimeMs: number | bigint): AikenFlowTxBuilder;
  validTo(unixTimeMs: number | bigint): AikenFlowTxBuilder;
  complete(): Promise<TxComplete>;
}

export interface AikenFlowLucid {
  newTx(): AikenFlowTxBuilder;
}

export interface LockedDatum {
  owner: string;
  amount: bigint;
  deadline: bigint;
}

export function lockedDatumToData(datum: LockedDatum): DataValue {
  return {
    constructor: 0,
    fields: [
      datum.owner,
      datum.amount,
      datum.deadline,
    ],
  };
}

